name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install  # Removed the -f app/pom.xml assuming pom.xml is in the root directory

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/*.jar  # Adjusted the path assuming the target directory is in the root

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Run unit tests
      run: mvn test  # Removed the -f app/pom.xml assuming pom.xml is in the root directory

    - name: Code coverage
      run: mvn jacoco:report  # Removed the -f app/pom.xml assuming pom.xml is in the root directory

    - name: Code quality analysis
      run: mvn sonar:sonar  # Removed the -f app/pom.xml assuming pom.xml is in the root directory

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to staging environment
      run: |
        echo "Deploying to staging..."
        # Add your deployment commands here

  notify:
    runs-on: ubuntu-latest
    if: failure()

    steps:
    - name: Send failure notification
      uses: apivideo/api.video-notifications-action@v1
      with:
        api_key: ${{ secrets.SLACK_API_KEY }}
        channel: '#your-slack-channel'
        message: 'Build or Deployment failed. Please check the logs.'
